### ISSUE TITLE
Error in importing module grass-section

### ISSUE THREAD

**Issue by rokoeh** [rafatieppo/SEBAL#2]
Hello.

While trying to run the sebal on landsat 8 images I got the following error:

```
C:\temp\teste_python>python sebal_v10.py
Traceback (most recent call last):
File "sebal_v10.py", line 15, in <module>
    from grass_session import Session
ImportError: No module named grass_session

```
At the same time when running `pip install grass-session` on cmd does not return output

```
C:\temp\teste_python>cd C:\Users\Roberto\anaconda3\Scripts

C:\Users\Roberto\anaconda3\Scripts>pip install grass-session

C:\Users\Roberto\anaconda3\Scripts>
```

And on Anaconda the module seems to be already installed

```
pip install grass-session
Requirement already satisfied: grass-session in c:\users\roberto\anaconda3\lib\site-packages (0.5)
Note: you may need to restart the kernel to use updated packages.

```

The landsat and DEM files all projected to the same CRS and their paths set in the lines 67, 68, 69. The DEM is with the filename MDT_Sebal.TIF.
GRASS session is open and running.

With best regards

**Comment by rafatieppo** [comment]
Hi, thanks for use this script. 

Actually, this error is from your  `grass_session` installation and not from the script. As standard,  the package  `grass_session` calls GRASS version 74, check you grass version.  Or, you can edit `grass_session` script replacing 74 by XX (XX is the your GRASS version e.g. 76). However you are using windows and I do not know how to handle packages in Windows. 

You have more question about it, please send me an email: rafaeltieppo<at>yahoo.com.br
Thanks.

**Comment by viru1907** [comment]
![20230310_190643](https://user-images.githubusercontent.com/126666117/224331153-e205267d-acdf-43d4-a21e-05c9ac8e6c26.jpg)
Grass.session module not import by above mention method

**Comment by rafatieppo** [comment]
I really sorry about that.
I do not know what is happening, I believe that is a Windows issue. Please, check the `space` in the path to assign the GRASSBIN in your code.

**Comment by ClaireTLM** [comment]
Hi @viru1907! I am having a similar issue like you. I received the same error message when I attempt to check if grass_session was working by typing 'from grass_session import session'. I was wondering if you managed to solve it? Thanks!

**Comment by rokoeh** [comment]
Hi guys. If you want the ETa from landsat images I recommend using the following method described here:

https://www.usgs.gov/media/files/landsat-4-9-collection-2-level-3-provisional-actual-evapotranspiration-product-guide

https://www.usgs.gov/media/files/eros-science-processing-architecture-demand-interface-user-guide

Hope this helps
